### ISSUE TITLE
[new model] our model achieves an 0.473 Spearman's Correlation on the DMS substitution benchmark

### ISSUE THREAD

**Issue by bzho3923** [OATML-Markslab/ProteinGym#11]
Hi ProteinGym Team,
Thank you for updating the ProteinGym Benchmark Dataset. We have evaluated our model (ProtSSN, on https://github.com/tyang816/ProtSSN) on the updated ProteinGym for DMS substitution scoring. Our model obtained an overall Spearman's correlation of 0.473 with the ensemble version. We kindly request you to double-check this result and, if confirmed accurate, update our performance on the leaderboard.

For your convenience, we have provided the mutant-specific scores by email. Please let us know if more information or documents are required from us. Thank you!

**Comment by pascalnotin** [comment]
Hi @bzho3923,

Thank you for raising the issue and congrats again on ProtSSN!

Following up on our email exchange, I am responding here with the same information for the benefit of other research teams interested in contributing new baselines (just updated the instructions on README accordingly). If you would like new baselines to be included in ProteinGym (ie., website, performance files, detailed scoring files), please submit a PR to our repo with the following two elements:
1. A new subfolder under proteingym/baselines named with your new model name. This subfolder should include a python scoring script similar to [this script](https://github.com/OATML-Markslab/ProteinGym/blob/main/proteingym/baselines/rita/compute_fitness.py), as well as all code dependencies required for the scoring script to run properly
2. An example bash script (e.g., under scripts/scoring_DMS_zero_shot) with all relevant hyperparameters for scoring, similar to [this script](https://github.com/OATML-Markslab/ProteinGym/blob/main/scripts/scoring_DMS_zero_shot/scoring_RITA_substitutions.sh)

Regarding model performance on DMS benchmarks, please ensure you are using the performance scripts we provide for consistency (e.g., [for zero-shot DMS benchmarks](https://github.com/OATML-Markslab/ProteinGym/blob/main/proteingym/performance_DMS_benchmarks.py)). These scripts correct for various biases (e.g., number of assays per protein family and function groupings). As a result, the aggregated performance post-correction is not the same as the arithmetic average across assays. For instance, the aggregate Spearman performance of TranceptEVE on the zero-shot DMS substitution benchmark is 0.474 pre-correction (ie., arithmetic average across all 217 assays), but 0.457 post-correction (reported performance in paper / website).

Best,
Pascal

**Comment by pascalnotin** [comment]
Hi @bzho3923 -- I have just merged in the PR with the ProtSSN dependencies added in. We will be refreshing our zero-shot substitution benchmark with ProtSSN scores shortly. Congrats again on the great work!

**Comment by bzho3923** [comment]
Hi Pascal,
Thank you very much for the update. Looking forward to seeing the new
leaderboard. :D

Best,
Bingxin
