### ISSUE TITLE
Bugs in `performance_DMS_benchmarks.py`?

### ISSUE THREAD

**Issue by tyang816** [OATML-Markslab/ProteinGym#15]
Hi, great work!
I have downloaded [zero_shot_substitutions_socres.zip](https://marks.hms.harvard.edu/proteingym/zero_shot_substitutions_scores.zip), but unfortunately I could not test the results directly.
1. I found `input_score_name` in config.json but never used in `performance_DMS_benchmarks.py`. I think you need this parameter to evaluate, but don't actually use it, which I'm confused about.
2. I met an error at line 297,  there is a `groupby` operation here, but an error will be reported for the dataframe. I would like to know how to run this script correctly.
![image](https://github.com/OATML-Markslab/ProteinGym/assets/68638646/f9fac147-3406-43de-a5d8-91ee1985b5eb)
Thanks a lot.

**Comment by tyang816** [comment]
When calculating metrics, the aggregation method is to aggregate 217 proteins through uniprot_id to obtain 187, and then average the 187 protein scores. Is this how it is done?
For transceptionEVE, I did not observe any change in the score, 0.4745->0.4742, not 0.457. Is there something wrong with the aggregation calculation method I understand?
Thank you so much.

**Comment by pascalnotin** [comment]
Dear Yang,

I just added instructions to compute model performance to the [README](https://github.com/OATML-Markslab/ProteinGym/blob/main/README.md?plain=1#L138). To address the few questions you raised above:
1. `input_score_name` is used in the merge script (see Step 4 of instructions)
2. This error should not occur if you follow steps 1-5 as per instructions. I just tested all steps from scratch and did not run into that error. Please let me know if the error still persists
3. The performance aggregation logic is summarized [here](https://github.com/OATML-Markslab/ProteinGym/blob/main/README.md?plain=1#L27). We control both for the [number of assays per protein family](https://github.com/OATML-Markslab/ProteinGym/blob/main/proteingym/performance_DMS_benchmarks.py#L298) and the [number of assays by function grouping](https://github.com/OATML-Markslab/ProteinGym/blob/main/proteingym/performance_DMS_benchmarks.py#L306)

Best,
Pascal

**Comment by tyang816** [comment]
Thank you very much for your detailed answer.
The reason for this error is that the version of `pandas` is wrong. I am using 2.1, and proteingym_env is 1.5.1.
```shell
pip uninstall pandas
pip install pandas==1.5.1
```
