### ISSUE TITLE
All substitution scores link in README results in 404

### ISSUE THREAD

**Issue by StephanHeijl** [OATML-Markslab/ProteinGym#19]
Dear ProteinGym team,

Once again thanks for your amazing work putting this resource together! 
In the README, you direct users to download this file that should contain all the scores for the diffrent DMS datasets:
```
https://marks.hms.harvard.edu/proteingym/scores_all_models_proteingym_substitutions.zip
```
Unfortunately, following this link results in a 404 error. If you have an updated overview file, it would be much appreciated.

Kind regards,
Stephan Heijl

**Comment by pascalnotin** [comment]
Dear Stephan,

Thank you for flagging the error with the download link. This was an outdated name for one of the the scoring files which we have just updated on the README. All downloads for files listed in the table should properly work, but please let us know if you run into any issues!

Kind regards,
Pascal

**Comment by StephanHeijl** [comment]
Much obliged Pascal, I found the relevant file, for future reference it is: 
https://marks.hms.harvard.edu/proteingym/DMS_supervised_substitutions_scores.zip
Kind regards,
Stephan Heijl
