### ISSUE TITLE
selection type categorization of DMS datasets

### ISSUE THREAD

**Issue by adalisan** [OATML-Markslab/ProteinGym#20]
For the assay type -stratified evaluation of  Mutational Effect prediction models, I noticed that the two datasets, SPIKE_SARS2_Starr_2020_expression and SPIKE_SARS2_Starr_2020_binding are categorized as "Binding"  in DMS_substitutions_Spearman_DMS_level.csv .  Were these DMS datasets both intentionally classified as  under  "Binding" assay type instead of  "Expression" and "Binding"?

**Comment by pascalnotin** [comment]
Dear Sancar - thank you for flagging! This is indeed an error, and we just pushed a commit to fix the reference file. We will update all results soon.

**Comment by loodvn** [comment]
Fixed in https://github.com/OATML-Markslab/ProteinGym/commit/151fbcae6ab07085d8546b864483717c322c4a4b
