### ISSUE TITLE
Missing scores of zero-shot clinical subsitutions

### ISSUE THREAD

**Issue by tuanqdinh** [OATML-Markslab/ProteinGym#22]
Hi, 

The link on GitHub for zero-shot clinical substitution scores (https://marks.hms.harvard.edu/proteingym/zero_shot_clinical_substitution_scores.zip) seems not working.

For the model scores downloaded directly from the webpage, I found that all score files are empty.

Can you please help fix this issue?
Thanks

**Comment by danieldritter** [comment]
Hi @tuanqdinh,

Thanks for catching this! Looks like there was an error when we zipped the files originally, and it only got the file structure without the content. I've updated the link now so it should be working correctly.

**Comment by tuanqdinh** [comment]
Thank you  for the prompt update. Can I ask what version of TranceptEVE model (L, M, S) was used for ClinVar (achieving 0.92 AUC)? 
And also, I find that the scores of TranceptEVE M and S are not complete (392 and 0 files compared 2525 files of model L).
Can you please double check?

Thanks

**Comment by danieldritter** [comment]
Hi Tuan,

The Clinical Scores for TranceptEVE all use TranceptEVE L. The incomplete
scores for the M and S models were included by accident, and I'll remove
those soon (they were from earlier partial scoring runs).

Best,
Daniel Ritter
