### ISSUE TITLE
Missing data for Tranception_no_retrieval/Tranception_M in zero_shot_clinical_indels_scores.zip

### ISSUE THREAD

**Issue by tekpinar** [OATML-Markslab/ProteinGym#34]
Hi,

I downloaded  zero_shot_clinical_indels_scores.zip from https://proteingym.org/download webpage. All of the csv files in Tranception_no_retrieval/Tranception_M seem to be empty. Unfortunately, it may lead to unfair comparisons if the data for a method is missing. 
I was wondering if you can take a look at the source of this problem. 

Best wishes,
Mustafa

**Comment by pascalnotin** [comment]
Thank you for flagging @tekpinar -- we will look into it asap

**Comment by pascalnotin** [comment]
Hi @tekpinar -- issue should be now fixed. Thank you @danieldritter for taking care of it!
Will close the issue, but @tekpinar feel free to reopen if anything else is missing.
Best,
Pascal
