### ISSUE TITLE
Discrepancy between DMS level values and reported averages 

### ISSUE THREAD

**Issue by tekpinar** [OATML-Markslab/ProteinGym#4]
Hello,
I have two question regarding the performances in the proteingym: 

1. I opened https://github.com/OATML-Markslab/ProteinGym/blob/main/Detailed_performance_files/Substitutions/Spearman/all_models_substitutions_Spearman_DMS_level.csv. Then, I calculated average Spearman values for TranceptEVE_L and EVE_ensemble values using both pandas and a spreadsheet program. The average values I obtain do not agree with the values reported in Summary_performance_all_models_substitutions_Spearman.csv. I was wondering if you ignore some DMS experiments from the average when you report the values in the summary file.  
2. I was wondering if all data points reported in the experiments (including multiple point measurements such as D170G:R187H in YAP1_HUMAN_Araya_2012.csv experiment) are calculated by the computational methods. I know that it may be difficult to answer that question for the other method reported in the ProteinGym but I am hoping that you have the answer for the methods developed in your lab (all tranception, tranceptEVE or EVE variants).
Thanks in advance,
Mustafa

**Comment by pascalnotin** [comment]
Dear Mustafa,

Apologies for the delayed response. To answer your two questions:

1. As reported in the [Tranception paper](https://proceedings.mlr.press/v162/notin22a.html) (Appendix E.1, last sentence) the computation approach at the time you asked the question was based on a 2-step process: 1) we were first aggregating all performance metrics at the Uniprot ID level and 2) we were then averaging the corresponding performance metrics across Uniprot IDs to obtain the final aggregate performance values reported everywhere. This was meant to remove potential biases stemming from having several assays for the same protein family. The exact logic for how things were computed back then is still available in the Tranception repo [here](https://github.com/OATML-Markslab/Tranception/blob/main/performance_analysis_proteingym.py#L292) (the former version of the ProteinGym codebase, now deprecated, was matching this code exactly).
Please note that in the new version we just released last week, we now also normalize by function grouping ("coarse_selection_type" in the updated reference files) when computing overall averages, to remove potential biases that would result from imbalances in the number of assays across function groupings. The exact computation approach is provided in the updated codebase [here](https://github.com/OATML-Markslab/ProteinGym/blob/main/proteingym/performance_DMS_benchmarks.py#L298C13-L298C48), and we recommend using this script to replicate all reported numbers in our paper / website.

2. All the data points corresponding to DMS scores that are provided in assay files (for instance [here](https://github.com/OATML-Markslab/ProteinGym/blob/main/README.md?plain=1#L85)) are all directly based on experimental values measured in the corresponding assays, for both singles and multiples -- these are not computed by us. The predictions scores for the various baselines (for example [here](https://github.com/OATML-Markslab/ProteinGym/blob/main/README.md?plain=1#L87)) are based on the official repo for each model. Generative models of full sequences, such as EVE or Tranception, handle multiple mutants directly. Pseudo-generative models, such as all ESM baselines, do not handle multiple mutants out-of-the-box and we resort to using the heuristics recommended by the authors to handle these (see [Meier et al.](https://www.biorxiv.org/content/10.1101/2021.07.09.450648v1) for the ESM suite -- scores for multiple mutants are obtained by summing the scores for the corresponding individual single mutants).

Please let me know if that addresses your questions. 

Kind regards,
Pascal

**Comment by pascalnotin** [comment]
Dear Mustafa,
I'm closing this issue as I believe the above addressed it. Please feel free to re-open if you have any further questions on this.
Best,
Pascal

**Comment by tekpinar** [comment]
Hello Pascal,
Thanks a lot for the answers.
Best wishes,
Mustafa
