### ISSUE TITLE
[Data Error] Taxon of FECA_ECOLI_Tsuboyama_2023_2D1U is wrong!

### ISSUE THREAD

**Issue by ginnm** [OATML-Markslab/ProteinGym#41]
The source organism of FECA_ECOLI_Tsuboyama_2023_2D1U is Escherichia coli, a Prokaryote.

**Comment by ginnm** [comment]
Fix in https://github.com/OATML-Markslab/ProteinGym/pull/40

**Comment by pascalnotin** [comment]
Hi @ginnm -- good catch and thank you for the PR! Just merged to main. 
Best,
Pascal
