### ISSUE TITLE
Error occurred while calculating the mean performance

### ISSUE THREAD

**Issue by jiaolifengmi** [OATML-Markslab/ProteinGym#42]
when sh ProteinGym/scripts/scoring_DMS_zero_shot/performance_indels.sh, some error in ProteinGym/proteingym/performance_DMS_benchmarks.py  line364 : Could not convert ['StabilityStabilityStabilityActivityStabilityStabilityOrganismalFitnessOrganismalFitnessOrganismalFitnessStabilityStabilityStabilityStabilityStabilityStabilityStabilityStabilityStabilityStabilityStabilityStabilityOrganismalFitnessStabilityExpressionStabilityStabilityStabilityStabilityStabilityStabilityStabilityStabilityStabilityOrganismalFitnessStabilityStabilityStabilityStabilityStabilityStabilityActivityOrganismalFitnessStabilityStabilityStabilityStabilityStabilityExpressionActivityStabilityStabilityStabilityStabilityStabilityStabilityStabilityStabilityStabilityStabilityStabilityStabilityStabilityStabilityStabilityStabilityStability'
 'A4_HUMANAMFR_HUMANARGR_ECOLIB1LPA6_ECOSMBBC1_YEASTBCHB_CHLTEBLAT_ECOLXCAPSD_AAV2SCAPSD_AAV2SCATR_CHLRECBPA2_HUMANCBX4_HUMANCSN4_MOUSECUE1_YEASTDN7A_SACS2DNJA1_HUMANDOCK1_MOUSEEPHB2_HUMANFECA_ECOLIHCP_LAMBDHECD1_HUMANHIS7_YEASTILF3_HUMANKCNJ2_MOUSEMAFG_MOUSEMBD11_ARATHMYO3_YEASTNKX31_HUMANNUSA_ECOLINUSG_MYCTUOBSCN_HUMANODP2_GEOSEOTU7A_HUMANP53_HUMANPIN1_HUMANPITX2_HUMANPKN1_HUMANPOLG_PESVPR40A_HUMANPSAE_SYNP2PTEN_HUMANQ8EG35_SHEONRAD_ANTMARCD1_ARATHRD23A_HUMANRPC1_BP434RS15_GEOSES22A1_HUMANS22A1_HUMANSAV1_MOUSESDA_BACSUSOX30_HUMANSPG2_STRSGSPTN1_CHICKSQSTM_MOUSESR43C_ARATHSRBS1_HUMANTCRG1_MOUSETHO1_YEASTTNKS2_HUMANUBE4B_HUMANUBR5_HUMANVG08_BPP22VILI_CHICKVRPI_BPT7YNZC_BACSU'
 'LowMediumMediumMediumHighMediumHighLowLowHighMediumHighMediumMediumMediumHighHighHighHighMediumMediumMediumHighMediumMediumMediumHighHighHighHighHighHighHighLowHighHighHighMediumMediumMediumMediumMediumHighMediumHighHighMediumMediumMediumHighMediumHighMediumHighMediumHighHighMediumHighHighHighMediumHighHighMediumMedium'
 'HumanHumanProkaryoteProkaryoteEukaryoteProkaryoteProkaryoteVirusVirusEukaryoteHumanHumanEukaryoteEukaryoteProkaryoteHumanEukaryoteHumanEukaryoteVirusHumanEukaryoteHumanEukaryoteEukaryoteEukaryoteEukaryoteHumanProkaryoteProkaryoteHumanProkaryoteHumanHumanHumanHumanHumanVirusHumanProkaryoteHumanProkaryoteEukaryoteEukaryoteHumanVirusProkaryoteHumanHumanEukaryoteProkaryoteHumanProkaryoteEukaryoteEukaryoteEukaryoteHumanEukaryoteEukaryoteHumanHumanHumanVirusEukaryoteVirusProkaryote'] to numeric

**Comment by pascalnotin** [comment]
Hi @jiaolifengmi - thank you for flagging. Could you please confirm whether you pulled the last version of our codebase (pushed ~5 hours before you posted your question), or the one before that?

**Comment by pascalnotin** [comment]
Hi @jiaolifengmi - closing this issue as I believe the bug is not present in the latest repo version, but feel free to re-open if needed.
Best,
Pascal
