### ISSUE TITLE
Why ESM-1v performs so well on DMS indels supervised benchmark?

### ISSUE THREAD

**Issue by LittletreeZou** [OATML-Markslab/ProteinGym#48]
Thank you for creating the benchmark!

For DMS indels supervised bechmark, `ESM-1v Embeddings` model achieves SOTA results on the indels benchmark, outperforming `Tranception Embeddings` and  `MSA Transformer Embeddings`. I wonder why it performs so well on the indels tasks. 

Is it because `ESM-1v Embedding` is using the ensembles of five released ESM-1v models?

**Comment by pascalnotin** [comment]
Hi @LittletreeZou,

Thank you for the question! We only use a single model checkpoint for ESM-1v in this analysis (`esm1v_t33_650M_UR90S_1`). The aggregate performance obtained with `ESM-1v` and `Tranception` embeddings are overall very close. Unlike what we were seeing for substitutions, the performance with `MSA Transformer` is however lower here, potentially owing to the typical challenges of alignment-based methods with indels. 

Best,
Pascal

**Comment by LittletreeZou** [comment]
Yes, I agree that the alignment-based methods seem to be not robust to dealing with indels data.

I am still very impressed by the performance of `ESM-1v` and trying to understand why.  So I used the `ProteinNPT` codebase and hyperparameter setting in the paper to reproduce the results of `ESM-1v` on the DMS indels supervised benchmark. As shown in the following table, on the 6 assays I tried, the reproduction results are worse than the scores reported in the leaderboard. I wonder if I missed anything that is not written in the paper or provided by the script. The configs I used are as follows. 
![Screenshot 2024-10-07 at 09 10 47](https://github.com/user-attachments/assets/f89a43ac-cf08-4b89-84c7-1c084f610d02)

```
{
    "model_type": "ESM1v_pred",
    "model_name_suffix": "Embeddings_ESM1v_final",
    "aa_embeddings": "ESM1v",
    "embedding_model_location": "ESM/ESM1v/esm1v_t33_650M_UR90S_1.pt",
    "augmentation": "zero_shot_fitness_predictions_covariate",
    "embed_dim": 1280,
    "max_positions": 1024,
    "target_prediction_head": "AA_embeddings_mean_pooled",
    "target_prediction_model": "CNN",
    "conv_kernel_size": 7,
    "weight_decay": 5e-2,
    "dropout": 0.1,
    "num_total_training_steps": 10000,
    "num_logging_training_steps": 10,
    "num_saving_training_steps": 20000,
    "num_eval_steps": 100,
    "num_warmup_steps": 100,
    "gradient_accumulation": 1,
    "training_num_assay_sequences_per_batch_per_gpu": 64,
    "eval_num_sequences_to_score_per_batch_per_gpu": 64,
    "seed": 2023
}
```

Besides, as reported in this table,  the average Spearman correlation across 5 folds is lower than the Spearman correlation on the whole dataset consistently across all 6 assays, which looks weird to me. Usually, the Spearman correlation computed on the whole dataset would be lower than the average fold Spearman correlation since they are using a different normalization between folds.

**Comment by pascalnotin** [comment]
Hi @LittletreeZou -- at first glance the parameters you have used above look correct. Have you tried on more assays since by any chance?
