### ISSUE TITLE
How to use TranceptEVE, the best model?

### ISSUE THREAD

**Issue by anton-bushuiev** [OATML-Markslab/ProteinGym#5]
Hi, thank you for a great work!

TranceptEVE L is the best model according to the [benchmark  website](https://www.proteingym.org/substitutions). But I cannot figure out how to use it on my data. Is it anywhere available? There are quite a lot of details in the TranceptEVE paper, which makes it not trivial to reimplement. Thank you!

**Comment by pascalnotin** [comment]
Dear Anton,

Thank you for your patience. We just released a significantly upgraded version of ProteinGym which now includes the code for TranceptEVE [here](https://github.com/OATML-Markslab/ProteinGym/tree/main/proteingym/baselines/trancepteve). To score with TranceptEVE,  there are two steps:
1. Train the EVE models for the protein family of interest, using the [following script](https://github.com/OATML-Markslab/ProteinGym/blob/main/scripts/scoring_DMS_zero_shot/training_EVE_models.sh)
2. Score with TranceptEVE, using the [following script](https://github.com/OATML-Markslab/ProteinGym/blob/main/scripts/scoring_DMS_zero_shot/scoring_TranceptEVE_substitutions.sh)

Please let us know if you have any questions.

Kind regards,
Pascal
