### ISSUE TITLE
Data 404 Not Found

### ISSUE THREAD

**Issue by nate-russell** [OATML-Markslab/ProteinGym#50]
Hello,

When trying to access https://marks.hms.harvard.edu/proteingym/DMS_ProteinGym_indels.zip I am getting 404 not found. Is it temporarily down or has it moved?

Thanks

**Comment by aaronkollasch** [comment]
Hello, sorry about the 404 errors - the ProteinGym files have indeed moved, to allow for multiple versions (also on Zenodo [v1.0](https://zenodo.org/records/13932633) and [v1.1](https://zenodo.org/records/13936340)).

The README's [Resources section](https://github.com/OATML-Markslab/ProteinGym?tab=readme-ov-file#resources) has been updated with the new links for individual files. For example, the v1.0 DMS_ProteinGym_indels.zip is now at https://marks.hms.harvard.edu/proteingym/ProteinGym_v1.0/DMS_ProteinGym_indels.zip

**Comment by nate-russell** [comment]
Thank you
