### ISSUE TITLE
How are the DMS score calculated and normalized

### ISSUE THREAD

**Issue by Joey-Xue** [OATML-Markslab/ProteinGym#52]
Thanks for providing the benchmark. I was recently trying benchmark some models on the dataset and found the DMS scores highly diverse for regression. For most of the assays, the max-min DMS score range from around -5 to 5, but for some assays like Q6WV13_9MAXI, D7PM05_CLYGR, the number ranges from 589 to 40000, which is clearly not in the same scale.
And for B2L11_HUMAN the min_max activity is 2640756.73 ~ 100215199.65. It seems that the score is not a normalized metric. 
I checked the github repository and ProteinGym paper but didn't find how the score was defined. Could you provide more clear definition of the score?
Thanks in advance for any kind help

**Comment by Joey-Xue** [comment]
Hello Pascal, thanks for your quick and comprehensive reply! The reference file provides exactly the information I need! So in the benchmark on protengym website, I wonder how the zero shot regression was performed as the DMS score was in different scales? 
One more question, the download link for the full proteinGYM-substitution dataset is not accessible now: https://marks.hms.harvard.edu/proteingym/DMS_ProteinGym_substitutions.zip 
Since I want to download the newest version of the dataset. Would you mind check when would the downloadable dataset be available again? Thanks again for your kind support.

**Comment by pascalnotin** [comment]
Hi @Joey-Xue,

For the first question, we standard normalize the targets in the regression setting, as done [here](https://github.com/OATML-Markslab/ProteinNPT/blob/master/proteinnpt/utils/data_utils.py#L109-L150).

For the second question, we recently added versioning to the benchmarks and updated the download links as described in the revised README [here](https://github.com/OATML-Markslab/ProteinGym/blob/main/README.md?plain=1#L101-L107).

**Comment by Joey-Xue** [comment]
Hi Pascal, thanks for your kind reply! Was pretty helpful
