### ISSUE TITLE
Project site downloads broken -- URL no found on server: DMS data, ClinVar data, MSAs, References

### ISSUE THREAD

**Issue by RMichae1** [OATML-Markslab/ProteinGym#54]
Hello ProteinGym team,

thank you all for the great contribution to the community!

Recently the linked files on the [project site Download tab](https://proteingym.org/download) have been broken, ie.:

1. [DMS Assay](https://marks.hms.harvard.edu/proteingym/DMS_ProteinGym_substitutions.zip)
2. [Clinical Variants](https://marks.hms.harvard.edu/proteingym/clinical_ProteinGym_substitutions.zip)
3. [MSAs](https://marks.hms.harvard.edu/proteingym/DMS_msa_files.zip)
4. [Reference files](https://proteingym.org/download)
etc. .

All linked files yield a **Not Found** error "The requested URL was not found on this server."

**Comment by pascalnotin** [comment]
Hi @RMichae1 - thank you for flagging! The issue should now be resolved.

**Comment by RMichae1** [comment]
Thanks @pascalnotin for the swift reply and fix!

**Comment by martinjankowiak** [comment]
@pascalnotin hello! please allow me to bring your attention to some broken links at https://proteingym.org/download under Supervised DMS Assay Scores:

https://marks.hms.harvard.edu/proteingym/DMS_supervised_substitutions_scores.csv
https://marks.hms.harvard.edu/proteingym/DMS_supervised_indels_scores.csv

thanks!

**Comment by danieldritter** [comment]
Sorry about this! I moved around some files on our end and accidentally broke those links. Should be fixed now!
