### ISSUE TITLE
How can I use this repo to run all 50 models on a different dataset? 

### ISSUE THREAD

**Issue by Yang-Wang-2020** [OATML-Markslab/ProteinGym#8]

**Comment by pascalnotin** [comment]
Dear Yang,

Assuming you are interested in the zero-shot baselines, we provide scripts in [this directory](https://github.com/OATML-Markslab/ProteinGym/tree/main/scripts/scoring_DMS_zero_shot) to run all baselines discussed in the paper. Please let us know if you run into any issues.

Kind regards,
Pascal

**Comment by pascalnotin** [comment]
Dear Yang,
I'm closing this issue as I believe the above addressed it. Please feel free to re-open if you have any further questions on this.
Best,
Pascal
