### ISSUE TITLE
Differences in set of assays marked ProteinGym v0.1 vs Tranception paper

### ISSUE THREAD

**Issue by timt51** [OATML-Markslab/ProteinGym#9]
I noticed some minor differences between the set of assays marked ProteinGym version 0.1 in the references files vs the set of assays listed in the Tranception paper:

- For the indels benchmark, the rubisco dataset from "Highly active rubiscos discovered by systematic interrogation of natural sequence diversity" by Davidi et al. seems to have been removed (not listed as being part of either version 0.1 or version 1). Is there any particular reason for its exclusion from the latest version of ProteinGym?
- For the substitutions benchmark, there are 78 unique "jo" marked version 0.1, but only 73 unique "jo" in the reference file from the Tranception publication. As a specific example, "A0A247D711_LISMN_Stadelmann_2021" is currently marked version 0.1, but I don't believe it was mentioned in the Tranception publication. Not a big deal, but just thought it would be good to let you know!

P.S. Thank you for all your hard work in putting these data together and making it available for the protein engineering community!

**Comment by pascalnotin** [comment]
Hi @timt51,

Thank you for the kind words! To answer your two questions:

1. We removed the Rubisco assay by Davidi et al. from the latest ProteinGym indel benchmark as it was not consistent with all other indel assays. In these other assays a WT sequence is mutated with one or several insertion(s)/deletion(s), but the assay from Davidi et al. was rather a collection of evolutionarily-related Rubisco sequences.

2. Thank you for pointing this out! You are correct -- a few assays were wrongly labeled as 0.1 while not being in the Tranception paper (these were in fact the first batch of assays we added to the new collection). I just pushed a new version to the repo with these version numbers corrected. Please note that there are now 71 "jo" marked as version 0.1 as we made the following changes to 2 assays that were in v0.1 (now marked as v1.0 given the updates):
- HSP82_YEAST_Flynn_2019: we used data from the same paper but opted for a different phenotype (see column "raw_DMS_phenotype_name")
- A4_HUMAN_Seuma_2021: we combined the data from the 2021 assay (10.7554/eLife.63364) with the newer A4_HUMAN assay from the same authors (10.1038/s41467-022-34742-3) to create "A4_HUMAN_Seuma_2022" in v1.0

Kind regards,
Pascal

**Comment by timt51** [comment]
1. This seems like a reasonable inclusion/exclusion criteria to me, but isn't the B1LPA6_ECOSM_Russ_2020_indels dataset also comprised in at least in part of "evolutionary-related" sequences (chorismate mutases) that differ significantly in sequence identity (Table S1)?
2. Thanks for fixing!

**Comment by pascalnotin** [comment]
Hi @timt51, 

The CM assay from Russ et al. includes both evolutionarily-related sequences (~1k) as well as designed sequences (~2k) with a bmDCA model trained on the corresponding MSA. The AAV assay from Sinai et al. is similar in that regard -- we split it into library (25k) vs designed indels (226k), with the former also containing a small number of natural sequences (~500). In both cases, the presence of a large proportion of non-natural sequences (designed or randomized) was the main factor in our decision to keep the corresponding assays. Lastly, given the increased focus on design in the new version of ProteinGym, we were also very keen to include assays w/ designed libraries and going relatively far in sequence space.

**Comment by timt51** [comment]
Gotcha, thanks for elaborating!
